name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'Base image for Dockerfile (e.g., ubuntu)'
        required: true
        default: 'ubuntu'
      docker_tag:
        description: 'Tag for the Base Docker image'
        required: true
        default: '22.04'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build --push --build-arg BASE_IMAGE=${{ github.event.inputs.base_image }}:${{ github.event.inputs.docker_tag }} \
        -t ${{ secrets.DOCKER_USERNAME }}/docker-systemd:${{ github.event.inputs.base_image }}-${{ github.event.inputs.docker_tag }}-systemctl-replacement \
        -f ./systemctl-replacement/Dockerfile ./systemctl-replacement
